In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

In [2]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3


In [3]:
X

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3]])

In [4]:
y

array([ 6,  8,  9, 11])

In [5]:
reg.fit(X,y)
reg.score(X, y)

1.0

In [6]:
reg.coef_



array([1., 2.])

In [7]:
reg.intercept_

3.0000000000000018

In [8]:

reg.predict(np.array([[3, 5]]))


array([16.])